# Generated by Django 4.1 on 2022-09-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, help_text='Фото блюда', null=True, upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
