# Generated by Django 2.2.16 on 2022-09-05 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_shoppinglist_favouriterecipe_favouriteauthor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteAuthor',
            new_name='Subscription',
        ),
    ]
